version: "3"

services:
  n1: &node_spec
    hostname: n1
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "ddbms_chat"
    env_file:
      - .docker/docker-mysql.env
    networks:
      nw:
        ipv4_address: 172.20.0.2
  n2:
    <<: *node_spec
    hostname: n2
    networks:
      nw:
        ipv4_address: 172.20.0.3
  n3:
    <<: *node_spec
    hostname: n3
    networks:
      nw:
        ipv4_address: 172.20.0.4
  n4:
    <<: *node_spec
    hostname: n4
    environment:
      - DO_DB_INIT=1
    networks:
      nw:
        ipv4_address: 172.20.0.5

networks:
  nw:
    ipam:
      config:
        - subnet: 172.20.0.0/24
